apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eatmtptdc-go
  janus-idp.io/tekton: eatmtptdc-go
  backstage.io/kubernetes-id: eatmtptdc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eatmtptdc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
